### ISSUE TITLE
Create content issue(s) based on the current wordpress page

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.github.io#3]

**Comment by tapaswenipathak** [comment]
## Documentation Landing Pages
0.  Mix of UPPER CASE + lower case + Title Case + Sentence case
1. Getting Started: https://www.openms.de/getting-started/
         <img width="1099" alt="Screenshot 2022-05-12 at 8 29 12 PM" src="https://user-images.githubusercontent.com/4143778/168105727-ed135409-564f-4a10-a909-b41da6cf7394.png">

     > [COMMANDLINE QUICK START](https://www.openms.de/getting-started/#c778d9c61c5ed2e15)
OR DO YOU WANT TO
      0. +. Delete.

    - Build Workflows with OpenMS: https://www.openms.de/getting-started/creating-workflows/
       - 0.
    - Command Line and Visualisation: https://www.openms.de/getting-started/command-line-and-visualisations/
       - 0.
    - Develop Your Own OpenMS Tools: https://www.openms.de/getting-started/develop-your-own-openms-tools/
       - 0.
    - Use OpenMS in CD/PD: https://www.openms.de/getting-started/proteome-and-compound-discoverer-integration/
       - 0.

     > DO YOU HAVE ANY SPECIFIC QUESTION OR ISSUE? 
Contact us directly at [support@open-ms.sourceforge.net](mailto:support@open-ms.sourceforge.net)
       
      For questions, contact us at [support@open-ms.sourceforge.net](mailto:support@open-ms.sourceforge.net)
3. Training: https://www.openms.de/training/ 
     0.
    - Training Events: https://www.openms.de/training/events/
       - 0.
    - Tutorials: https://www.openms.de/tutorials/
       - 0.
    - Additional Materials: https://www.openms.de/training/materials/
       - 0.
       -  > Related materials helpful for deeper understanding of the general concepts as well as advanced literature (online lectures, related tutorials etc.)
        
           Educational material explaining general concepts and advanced literature; including lectures and tutorials.
5. Downloads: https://www.openms.de/downloads/
        
      > Download OpenMS installer for the different platforms. If you are unsure which version you need for your analysis please consult the getting started page.
         
      Download OpenMS installer for supported platforms. More details about choosing a version(s) as per your requirement can be found on the [getting started page](https://www.openms.de/getting-started/).

    - Installer: https://www.openms.de/downloads/
    - Workflows: https://www.openms.de/workflows/
    - Tutorials: https://www.openms.de/tutorials/ 
6. Applications: https://www.openms.de/applications/
    - Featured tools
    - Featured workflows
7. News: https://www.openms.de/news/
    - Latest News
    - News Archive
8. Support: https://www.openms.de/support/
    - OpenMS in KNIME →
        - → Tutorials: https://www.openms.de/tutorials/
        - → KNIME Quick Start Guide: https://tech.knime.org/files/KNIME_quickstart.pdf, → KNIME Documentation: https://docs.knime.com/, KNIME Forum: https://www.knime.com/forum/openms
    - Visualisation in TOPPView and Command Line Usage →
        - → Command Line and Visualisations → https://www.openms.de/getting-started/command-line-and-visualisations/
        - → Tutorials: https://www.openms.de/tutorials/
    - OpenMS in Proteome Discoverer / Compound Discoverer →
        - → 
            > If you have questions regarding the OpenMS nodes integrated into PD and CD, you can contact the OpenMS developer team through GitHub or the mailing lists mentioned below.
        - PD and CD Product Page Link →
            - https://www.thermofisher.com/order/catalog/product/IQLAAEGABSFAKJMAUH
                > Error:This product (Catalog number IQLAAEGABSFAKJMAUH) has been discontinued. Please contact [Customer Service](https://www.thermofisher.com/in/en/home/technical-resources/contact-us.IQLAAEGABSFAKJMAUH.html?supportType=SL) for possible alternatives.
            - https://www.thermofisher.com/order/catalog/product/IQLAAEGABSFAOXMBDD
                > Error:This product (Catalog number IQLAAEGABSFAOXMBDD) has been discontinued and replaced by Catalog number [OPTON-30561](https://www.thermofisher.com/order/catalog/product/OPTON-30561).
    - Mailing Lists →
        - → [SourceForge] Mailing List: open-ms-announcements https://sourceforge.net/projects/open-ms/lists/open-ms-announcements
        - → [SourceForge] OpenMS General Mailing List: https://sourceforge.net/projects/open-ms/lists/open-ms-general
    - OpenMS Documentation →
        - → OpenMS / TOPP documentation: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/index.html
        - → Developer C++ Quickstart Guide: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/OpenMS_tutorial.html
    - pyOpenMS Documentation →
        - → [ReadTheDocs] https://pyopenms.readthedocs.io/en/latest/
    - Reach us on GitHub
        - [GitHub] Issue Tracker: https://github.com/OpenMS/OpenMS/issues
    - Contributors: https://www.openms.de/people/
        - Team
        - Contributing Institutions
        - Funding
9. Publications: https://www.openms.de/publications/
    - Publications by year
        → 2021
        → 2020
        → ..…….
        → 2005
10. Jobs: https://www.openms.de/jobs/
![](https://paper-attachments.dropbox.com/s_049CCB812FD6A3FF3522A731E167FE378AC39F1414B9ABFDE48361E06B7571AB_1651215084241_Screenshot+2022-04-29+at+12.21.18+PM.png)

    
    
    
    
    
    



    - https://github.com/OpenMS/OpenMS/wiki
    - https://github.com/OpenMS/OpenMS/wiki/Developer-FAQ
11. Wiki


## Languages
1. English
2. German: Search Bar
![](https://paper-attachments.dropbox.com/s_049CCB812FD6A3FF3522A731E167FE378AC39F1414B9ABFDE48361E06B7571AB_1651215232208_Screenshot+2022-04-29+at+12.23.29+PM.png)

## Images
- [ ] Screenshot Resolution
- [ ] Environment
<img width="1440" alt="Screenshot 2022-05-12 at 7 09 05 PM" src="https://user-images.githubusercontent.com/4143778/168088265-308ea00d-056f-482c-b470-5967a9a70ebe.png">


Ref: https://paper.dropbox.com/doc/OpenMS-Documentation--BhWKWs3~ihDyy6PJdM6EXV0KAg-2b0x4FsrcFSQD93bTOgnD#:uid=109020399859834235455680&h2=Public:-Documentation-Landing-.

**Comment by jpfeuffer** [comment]
Nice. But I think the Landing page structure is not really a *content* issue. I think this should go into either the "menu structure" issue or in a separate issue. And it is more a status quo. I do not see any "issue/problem".

**Comment by tapaswenipathak** [comment]
(editing).
